extend schema 
  @link(url: "https://specs.apollo.dev/federation/v2.6", 
    import: ["@key"])

"My Class"
type MyClass @key(fields: "id") {
  "Unique Identifier"
  id: ID!
}

"Query"
type Query {
 "Return MyClass"
  myClass: MyClass
}
